# Generated by Codex on 2026-07-15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodPrepareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(db_index=True)),
                ('prepare_detail', models.CharField(max_length=20)),
                ('prepare_date', models.DateField(db_index=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('record_note', models.CharField(max_length=20)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 't_good_prepare_record',
                'unique_together': {('shop_id', 'prepare_date')},
            },
        ),
    ]
